package MyApp;

import java.util.*;
import javax.swing.*;

/**
 *
 * @author Angela
 */
public class OrderDisplay extends javax.swing.JFrame {
    public OrderDisplay() {
        initComponents();
        setLocationRelativeTo(null);
        
        // disable the place order menu on the order display
        file_placeOrder.setEnabled(false);
        file_displayOrder.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        drinkSelectionButtonGroup = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        yourOrderLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderTextArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        file_placeOrder = new javax.swing.JMenuItem();
        file_clearOrder = new javax.swing.JMenuItem();
        file_displayOrder = new javax.swing.JMenuItem();
        file_exit = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenu();
        edit_menuSelection = new javax.swing.JMenuItem();
        edit_drink = new javax.swing.JMenuItem();
        edit_specialRequest = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        help_about = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(102, 102, 102));

        jPanel1.setBackground(new java.awt.Color(247, 247, 247));

        yourOrderLabel.setFont(new java.awt.Font("Cambria", 0, 36)); // NOI18N
        yourOrderLabel.setText("Your Order");

        orderTextArea.setEditable(false);
        orderTextArea.setColumns(20);
        orderTextArea.setFont(new java.awt.Font("DialogInput", 0, 19)); // NOI18N
        orderTextArea.setRows(5);
        jScrollPane1.setViewportView(orderTextArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addComponent(yourOrderLabel)
                .addGap(165, 165, 165))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(yourOrderLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 234, 222));
        jMenuBar1.setForeground(new java.awt.Color(255, 234, 222));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        menuFile.setBackground(new java.awt.Color(255, 178, 117));
        menuFile.setText(" File    ");
        menuFile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        file_placeOrder.setText("Place the Order");
        file_placeOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                file_placeOrderActionPerformed(evt);
            }
        });
        menuFile.add(file_placeOrder);

        file_clearOrder.setText("Clear the Order");
        file_clearOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                file_clearOrderActionPerformed(evt);
            }
        });
        menuFile.add(file_clearOrder);

        file_displayOrder.setText("Display the Order");
        file_displayOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                file_displayOrderActionPerformed(evt);
            }
        });
        menuFile.add(file_displayOrder);

        file_exit.setText("Exit");
        file_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                file_exitActionPerformed(evt);
            }
        });
        menuFile.add(file_exit);

        jMenuBar1.add(menuFile);

        menuEdit.setText(" Edit    ");
        menuEdit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        edit_menuSelection.setText("Menu Selection");
        edit_menuSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_menuSelectionActionPerformed(evt);
            }
        });
        menuEdit.add(edit_menuSelection);

        edit_drink.setText("Drink");
        edit_drink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_drinkActionPerformed(evt);
            }
        });
        menuEdit.add(edit_drink);

        edit_specialRequest.setText("Special Request");
        edit_specialRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_specialRequestActionPerformed(evt);
            }
        });
        menuEdit.add(edit_specialRequest);

        jMenuBar1.add(menuEdit);

        menuHelp.setText(" Help    ");
        menuHelp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        help_about.setText("About");
        help_about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                help_aboutActionPerformed(evt);
            }
        });
        menuHelp.add(help_about);

        jMenuBar1.add(menuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void file_placeOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_file_placeOrderActionPerformed
        // this menu is disabled as the order is already displayed.
    }//GEN-LAST:event_file_placeOrderActionPerformed

    private void file_clearOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_file_clearOrderActionPerformed
        clearOrderAndOpenDinerMenu();
    }//GEN-LAST:event_file_clearOrderActionPerformed

    private void file_displayOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_file_displayOrderActionPerformed
        // the order is already being displayed
    }//GEN-LAST:event_file_displayOrderActionPerformed

    private void edit_menuSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_menuSelectionActionPerformed
        DinerMenu dinerMenu = new DinerMenu();
        dinerMenu.setVisible(true);
        this.dispose();
        
        dinerMenu.resetMenuSelection();
    }//GEN-LAST:event_edit_menuSelectionActionPerformed

    private void edit_drinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_drinkActionPerformed
        DinerMenu dinerMenu = new DinerMenu();
        dinerMenu.setVisible(true);
        this.dispose();
        
        dinerMenu.resetDrinkSelection();
    }//GEN-LAST:event_edit_drinkActionPerformed

    private void edit_specialRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_specialRequestActionPerformed
        DinerMenu dinerMenu = new DinerMenu();
        dinerMenu.setVisible(true);
        this.dispose();
        
        dinerMenu.resetSpecialRequest();
    }//GEN-LAST:event_edit_specialRequestActionPerformed

    private void help_aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_help_aboutActionPerformed
        String aboutMessage = "<html><div style='text-align: center; font-size:16px;'>" +
                "Mini Diner Application<br>" +
                "By: Angela Abarquez<br><br>" +
                "Version 1.0" +
                "</div></html>";

        // Display the JOptionPane with HTML-formatted text
        JOptionPane.showMessageDialog(this, aboutMessage, "Information", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_help_aboutActionPerformed

    private void file_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_file_exitActionPerformed
        // Close the application
        System.exit(0);
    }//GEN-LAST:event_file_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderDisplay().setVisible(true);
            }
        });
    }
    
    public void setOrderDetails(String orderDetails) {
        orderTextArea.setText(orderDetails);
    }
    
    private void clearOrderAndOpenDinerMenu(){
        // Display a confirmation dialog
        int option = JOptionPane.showConfirmDialog(this,
                "Your current order will be cleared. Do you wish to proceed?",
                "Clear the Order",
                JOptionPane.YES_NO_OPTION);

        if (option == JOptionPane.YES_OPTION) {
            // If user clicks Yes, open DinerMenu and close OrderDisplay
            DinerMenu dinerMenu = new DinerMenu();
            dinerMenu.setVisible(true);
            this.dispose(); // Close the current window

            // Reset the contents of DinerMenu (assuming you have a method for that)
            dinerMenu.resetMenuContents();
        } else {
            // If user clicks No, do nothing and stay on OrderDisplay
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup drinkSelectionButtonGroup;
    private javax.swing.JMenuItem edit_drink;
    private javax.swing.JMenuItem edit_menuSelection;
    private javax.swing.JMenuItem edit_specialRequest;
    private javax.swing.JMenuItem file_clearOrder;
    private javax.swing.JMenuItem file_displayOrder;
    private javax.swing.JMenuItem file_exit;
    private javax.swing.JMenuItem file_placeOrder;
    private javax.swing.JMenuItem help_about;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JTextArea orderTextArea;
    private javax.swing.JLabel yourOrderLabel;
    // End of variables declaration//GEN-END:variables
}
