package MyApp;

import MyLib.User.Client;
import MyLib.User.Admin;
import MyLib.User.User;
import MyLib.User.Admin;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import javax.swing.JFrame;
import javax.swing.JTextField;
import MyLib.User.Admin;
import java.util.ArrayList;

/**
 *
 * @author Angela
 */
    public class Register extends javax.swing.JFrame {
    private enum AccountType{
        CLIENT, ADMIN
    }
    private AccountType selectedAccountType = AccountType.CLIENT;
    private ArrayList<User> users; // Add an instance field to store users
    
    public Register() {
        initComponents();
        this.users = users; // Initialize the users list
        
        // Make the JFrame not resizable (maximizable)
        setResizable(false);
        
        // Set the cursor for the button to hand cursor when hovered
        button_client.setCursor(new Cursor(Cursor.HAND_CURSOR));
        button_admin.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        //add placeholder style
        addPlaceholderStyle(client_username);   //for client form
        addPlaceholderStyle(client_pass);
        addPlaceholderStyle(client_fullname);
        addPlaceholderStyle(client_cpnum);
        
        addPlaceholderStyle(admin_username);   //for admin form
        addPlaceholderStyle(admin_pass);
        addPlaceholderStyle(admin_fullname);
        addPlaceholderStyle(admin_id);
        
        // Set the initial focus to the choice of Client or Admin Account
        accountTypeComboBox.requestFocus();
        
        // Set the default selected account type to "Client"
        accountTypeComboBox.setSelectedItem("Client");
        selectedAccountType = AccountType.CLIENT;

        // Show the client registration panel
        showClientPanel();
    }
    private void showClientPanel() {
        clientPanel.setVisible(true);
        adminPanel.setVisible(false);
    }
    private void showAdminPanel() {
        clientPanel.setVisible(false);
        adminPanel.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        button_login = new javax.swing.JButton();
        clientPanel = new javax.swing.JPanel();
        client_username = new javax.swing.JTextField();
        client_pass = new javax.swing.JTextField();
        client_fullname = new javax.swing.JTextField();
        client_cpnum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        button_client = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        asterisk = new javax.swing.JLabel();
        asterisk1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        adminPanel = new javax.swing.JPanel();
        admin_username = new javax.swing.JTextField();
        admin_pass = new javax.swing.JTextField();
        admin_fullname = new javax.swing.JTextField();
        admin_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        asterisk2 = new javax.swing.JLabel();
        asterisk3 = new javax.swing.JLabel();
        asterisk4 = new javax.swing.JLabel();
        button_admin = new javax.swing.JButton();
        accountTypeComboBox = new javax.swing.JComboBox<>();
        logoRedDoor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1018, 628));

        jPanel1.setBackground(new java.awt.Color(242, 244, 243));

        jLabel6.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel6.setText("Already have an account?");

        button_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/button-login2.png"))); // NOI18N
        button_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_loginActionPerformed(evt);
            }
        });

        clientPanel.setBackground(new java.awt.Color(255, 255, 255));

        client_username.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        client_username.setText("Username");
        client_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                client_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                client_usernameFocusLost(evt);
            }
        });
        client_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client_usernameActionPerformed(evt);
            }
        });

        client_pass.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        client_pass.setText("Password");
        client_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                client_passFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                client_passFocusLost(evt);
            }
        });
        client_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client_passActionPerformed(evt);
            }
        });

        client_fullname.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        client_fullname.setText("Full Name");
        client_fullname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                client_fullnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                client_fullnameFocusLost(evt);
            }
        });
        client_fullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client_fullnameActionPerformed(evt);
            }
        });

        client_cpnum.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        client_cpnum.setText("09*********");
        client_cpnum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                client_cpnumFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                client_cpnumFocusLost(evt);
            }
        });
        client_cpnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client_cpnumActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Lucida Fax", 0, 26)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Client Account");

        button_client.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        button_client.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/button-create-clientaccount.png"))); // NOI18N
        button_client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_clientActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Client Username");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Password");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Client Full Name");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Contact Number");

        asterisk.setBackground(new java.awt.Color(255, 255, 255));
        asterisk.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        asterisk.setForeground(new java.awt.Color(255, 0, 0));
        asterisk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        asterisk.setText("*");

        asterisk1.setBackground(new java.awt.Color(255, 255, 255));
        asterisk1.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        asterisk1.setForeground(new java.awt.Color(255, 0, 0));
        asterisk1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        asterisk1.setText("*");

        javax.swing.GroupLayout clientPanelLayout = new javax.swing.GroupLayout(clientPanel);
        clientPanel.setLayout(clientPanelLayout);
        clientPanelLayout.setHorizontalGroup(
            clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clientPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clientPanelLayout.createSequentialGroup()
                        .addGroup(clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(clientPanelLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(asterisk1))
                            .addGroup(clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(client_fullname, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(client_pass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                                .addComponent(client_cpnum, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                                .addGroup(clientPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(asterisk))
                                .addComponent(client_username, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clientPanelLayout.createSequentialGroup()
                        .addComponent(button_client, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114))))
        );
        clientPanelLayout.setVerticalGroup(
            clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(asterisk))
                .addGap(1, 1, 1)
                .addComponent(client_username, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(asterisk1))
                .addGap(2, 2, 2)
                .addComponent(client_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(2, 2, 2)
                .addComponent(client_fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(1, 1, 1)
                .addComponent(client_cpnum, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(button_client, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        jLabel7.setFont(new java.awt.Font("Lucida Fax", 0, 38)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText(" Create an Account");

        adminPanel.setBackground(new java.awt.Color(255, 255, 255));

        admin_username.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        admin_username.setText("Username");
        admin_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                admin_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                admin_usernameFocusLost(evt);
            }
        });
        admin_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_usernameActionPerformed(evt);
            }
        });

        admin_pass.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        admin_pass.setText("Password");
        admin_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                admin_passFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                admin_passFocusLost(evt);
            }
        });
        admin_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_passActionPerformed(evt);
            }
        });

        admin_fullname.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        admin_fullname.setText("Full Name");
        admin_fullname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                admin_fullnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                admin_fullnameFocusLost(evt);
            }
        });
        admin_fullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_fullnameActionPerformed(evt);
            }
        });

        admin_id.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        admin_id.setText("*123");
        admin_id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                admin_idFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                admin_idFocusLost(evt);
            }
        });
        admin_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_idActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Fax", 0, 26)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Admin Account");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Admin Username");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Password");

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Admin Full Name");

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Admin ID");

        asterisk2.setBackground(new java.awt.Color(255, 255, 255));
        asterisk2.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        asterisk2.setForeground(new java.awt.Color(255, 0, 0));
        asterisk2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        asterisk2.setText("*");

        asterisk3.setBackground(new java.awt.Color(255, 255, 255));
        asterisk3.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        asterisk3.setForeground(new java.awt.Color(255, 0, 0));
        asterisk3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        asterisk3.setText("*");

        asterisk4.setBackground(new java.awt.Color(255, 255, 255));
        asterisk4.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        asterisk4.setForeground(new java.awt.Color(255, 0, 0));
        asterisk4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        asterisk4.setText("*");

        button_admin.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        button_admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/button-create-adminaccount.png"))); // NOI18N
        button_admin.setMaximumSize(new java.awt.Dimension(289, 51));
        button_admin.setMinimumSize(new java.awt.Dimension(289, 51));
        button_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_adminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adminPanelLayout = new javax.swing.GroupLayout(adminPanel);
        adminPanel.setLayout(adminPanelLayout);
        adminPanelLayout.setHorizontalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminPanelLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminPanelLayout.createSequentialGroup()
                        .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(admin_username, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(admin_fullname, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(admin_id, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                                .addGroup(adminPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(asterisk3))
                                .addComponent(admin_pass))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, adminPanelLayout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(asterisk2))
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, adminPanelLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(asterisk4)))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminPanelLayout.createSequentialGroup()
                        .addComponent(button_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114))))
        );
        adminPanelLayout.setVerticalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(asterisk2))
                .addGap(1, 1, 1)
                .addComponent(admin_username, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(asterisk3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(admin_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(2, 2, 2)
                .addComponent(admin_fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(asterisk4))
                .addGap(3, 3, 3)
                .addComponent(admin_id, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(button_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        accountTypeComboBox.setFont(new java.awt.Font("Candara", 1, 15)); // NOI18N
        accountTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Client", "Admin" }));
        accountTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountTypeComboBoxActionPerformed(evt);
            }
        });

        logoRedDoor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reddoor.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(logoRedDoor)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(accountTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(clientPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(adminPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(button_login, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(logoRedDoor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accountTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(adminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clientPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_login, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accountTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountTypeComboBoxActionPerformed
        String selectedType = accountTypeComboBox.getSelectedItem().toString();

        if (selectedType.equals("Client")) {
            selectedAccountType = AccountType.CLIENT;
            showClientPanel();
        } else if (selectedType.equals("Admin")) {
            selectedAccountType = AccountType.ADMIN;
            showAdminPanel();
        }
    }//GEN-LAST:event_accountTypeComboBoxActionPerformed

    private void button_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_adminActionPerformed
        try
        {
            String email = admin_username.getText();
            String pass = admin_pass.getText();
            String name = admin_fullname.getText();
            int empID = Integer.parseInt(admin_id.getText());

            if(email.isEmpty() || pass.isEmpty() || name.isEmpty() || admin_id.getText().isEmpty()){
                myError("Please input a valid email, password, name, and employee id.");
            }
            else{
                //creates new admin object
                User admin = new Admin(email, pass, name, empID); //polymorphism
                User.users.add(admin);

                //redirects to login page
                redirectLogin();
            }
        }catch(Exception e)
        {
            myError("Input a valid email, password, name, and admin ID (numeric).");
        }
    }//GEN-LAST:event_button_adminActionPerformed

    private void admin_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_idActionPerformed
        if(!(admin_id.getText().isEmpty())){
            button_admin.doClick(); // Enter to click the login button for admin
        }
    }//GEN-LAST:event_admin_idActionPerformed

    private void admin_idFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_admin_idFocusLost
        if(admin_id.getText().length()==0){
            //add Placeholder style
            addPlaceholderStyle(admin_id);
            admin_id.setText("*123");
        }
    }//GEN-LAST:event_admin_idFocusLost

    private void admin_idFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_admin_idFocusGained
        if(admin_id.getText().equals("*123")){
            admin_id.setText(null);
            admin_id.requestFocus();
            //remove placeholder style
            removePlaceholderStyle(admin_id);
        }
    }//GEN-LAST:event_admin_idFocusGained

    private void admin_fullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_fullnameActionPerformed
        if(!(admin_fullname.getText().isEmpty())){
            admin_id.requestFocus();
        }
    }//GEN-LAST:event_admin_fullnameActionPerformed

    private void admin_fullnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_admin_fullnameFocusLost
        if(admin_fullname.getText().length()==0){
            //add Placeholder style
            addPlaceholderStyle(admin_fullname);
            admin_fullname.setText("Full Name");
        }
    }//GEN-LAST:event_admin_fullnameFocusLost

    private void admin_fullnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_admin_fullnameFocusGained
        if(admin_fullname.getText().equals("Full Name")){
            admin_fullname.setText(null);
            admin_fullname.requestFocus();
            //remove placeholder style
            removePlaceholderStyle(admin_fullname);
        }
    }//GEN-LAST:event_admin_fullnameFocusGained

    private void admin_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_passActionPerformed
        if(!(admin_pass.getText().isEmpty())){
            admin_fullname.requestFocus();
        }
    }//GEN-LAST:event_admin_passActionPerformed

    private void admin_passFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_admin_passFocusLost
        if(admin_pass.getText().length()==0){
            //add Placeholder style
            addPlaceholderStyle(admin_pass);
            admin_pass.setText("Password");
        }
    }//GEN-LAST:event_admin_passFocusLost

    private void admin_passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_admin_passFocusGained
        if(admin_pass.getText().equals("Password")){
            admin_pass.setText(null);
            admin_pass.requestFocus();
            //remove placeholder style
            removePlaceholderStyle(admin_pass);
        }
    }//GEN-LAST:event_admin_passFocusGained

    private void admin_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_usernameActionPerformed
        if(!(admin_username.getText().isEmpty())){
            admin_pass.requestFocus(); // Enter to click the login button
        }
    }//GEN-LAST:event_admin_usernameActionPerformed

    private void admin_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_admin_usernameFocusLost
        if(admin_username.getText().length()==0){
            //add Placeholder style
            addPlaceholderStyle(admin_username);
            admin_username.setText("Username");
        }
    }//GEN-LAST:event_admin_usernameFocusLost

    private void admin_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_admin_usernameFocusGained
        if(admin_username.getText().equals("Username")){
            admin_username.setText(null);
            admin_username.requestFocus();
            //remove placeholder style
            removePlaceholderStyle(admin_username);
        }
    }//GEN-LAST:event_admin_usernameFocusGained

    private void button_clientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_clientActionPerformed
        String email = client_username.getText();
        String pass = client_pass.getText();
        String name = client_fullname.getText();
        String contactNum = client_cpnum.getText();
        
        if(email.isEmpty() || pass.isEmpty() || name.isEmpty() || contactNum.isEmpty()){
            myError("Please input a valid email, password, name, and contact number.");
        }
        else{
            //creates new client object
            User client = new Client(email, pass, name, contactNum); //polymorphism
            User.users.add(client);

            //redirects to login page
            redirectLogin();
        }
    }//GEN-LAST:event_button_clientActionPerformed

    private void client_cpnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_client_cpnumActionPerformed
        if(!(client_cpnum.getText().isEmpty())){
            button_client.doClick(); // Enter to click the login button for client
        }
    }//GEN-LAST:event_client_cpnumActionPerformed

    private void client_cpnumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_client_cpnumFocusLost
        if(client_cpnum.getText().length()==0){
            //add Placeholder style
            addPlaceholderStyle(client_cpnum);
            client_cpnum.setText("09*********");
        }
    }//GEN-LAST:event_client_cpnumFocusLost

    private void client_cpnumFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_client_cpnumFocusGained
        if(client_cpnum.getText().equals("09*********")){
            client_cpnum.setText(null);
            client_cpnum.requestFocus();
            //remove placeholder style
            removePlaceholderStyle(client_cpnum);
        }
    }//GEN-LAST:event_client_cpnumFocusGained

    private void client_fullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_client_fullnameActionPerformed
        if(!(client_fullname.getText().isEmpty())){
            client_cpnum.requestFocus();
        }
    }//GEN-LAST:event_client_fullnameActionPerformed

    private void client_fullnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_client_fullnameFocusLost
        if(client_fullname.getText().length()==0){
            //add Placeholder style
            addPlaceholderStyle(client_fullname);
            client_fullname.setText("Full Name");
        }
    }//GEN-LAST:event_client_fullnameFocusLost

    private void client_fullnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_client_fullnameFocusGained
        if(client_fullname.getText().equals("Full Name")){
            client_fullname.setText(null);
            client_fullname.requestFocus();
            //remove placeholder style
            removePlaceholderStyle(client_fullname);
        }
    }//GEN-LAST:event_client_fullnameFocusGained

    private void client_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_client_passActionPerformed
        if(!(client_pass.getText().isEmpty())){
            client_fullname.requestFocus();
        }
    }//GEN-LAST:event_client_passActionPerformed

    private void client_passFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_client_passFocusLost
        if(client_pass.getText().length()==0){
            //add Placeholder style
            addPlaceholderStyle(client_pass);
            client_pass.setText("Password");
        }
    }//GEN-LAST:event_client_passFocusLost

    private void client_passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_client_passFocusGained
        if(client_pass.getText().equals("Password")){
            client_pass.setText(null);
            client_pass.requestFocus();
            //remove placeholder style
            removePlaceholderStyle(client_pass);
        }
    }//GEN-LAST:event_client_passFocusGained

    private void client_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_client_usernameActionPerformed
        if(!(client_username.getText().isEmpty())){
            client_pass.requestFocus();
        } // Move the focus to the password field
    }//GEN-LAST:event_client_usernameActionPerformed

    private void client_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_client_usernameFocusLost
        if(client_username.getText().length()==0){
            //add Placeholder style
            addPlaceholderStyle(client_username);
            client_username.setText("Username");
        }
    }//GEN-LAST:event_client_usernameFocusLost

    private void client_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_client_usernameFocusGained
        if(client_username.getText().equals("Username")){
            client_username.setText(null);
            client_username.requestFocus();
            //remove placeholder style
            removePlaceholderStyle(client_username);
        }
    }//GEN-LAST:event_client_usernameFocusGained

    private void button_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_loginActionPerformed
        //redirect to login page
        redirectLogin();
    }//GEN-LAST:event_button_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
    }
    
    public void addPlaceholderStyle(JTextField textField){
        Font font = textField.getFont();
        font = font.deriveFont(Font.ITALIC);
        textField.setFont(font);
        textField.setForeground(Color.lightGray);
        
    }
    
    public void removePlaceholderStyle(JTextField textField){
        Font font = textField.getFont();
        font = font.deriveFont(Font.PLAIN);
        textField.setFont(font);
        textField.setForeground(Color.black);
    }
    
        public void redirectLogin(){
        Login login = new Login();
        login.setLocationRelativeTo(null);
        login.setVisible(true);
        login.pack();
        this.dispose();
    }
    
    public void myError(String errorText){
        ErrorPopUp err = new ErrorPopUp(new JFrame("frame"),true);
        err.setjLabel2(errorText);
        err.setLocationRelativeTo(null);
        err.setVisible(true);        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> accountTypeComboBox;
    private javax.swing.JPanel adminPanel;
    private javax.swing.JTextField admin_fullname;
    private javax.swing.JTextField admin_id;
    private javax.swing.JTextField admin_pass;
    private javax.swing.JTextField admin_username;
    private javax.swing.JLabel asterisk;
    private javax.swing.JLabel asterisk1;
    private javax.swing.JLabel asterisk2;
    private javax.swing.JLabel asterisk3;
    private javax.swing.JLabel asterisk4;
    private javax.swing.JButton button_admin;
    private javax.swing.JButton button_client;
    private javax.swing.JButton button_login;
    private javax.swing.JPanel clientPanel;
    private javax.swing.JTextField client_cpnum;
    private javax.swing.JTextField client_fullname;
    private javax.swing.JTextField client_pass;
    private javax.swing.JTextField client_username;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoRedDoor;
    // End of variables declaration//GEN-END:variables


}
