package MyApp;

import MyLib.LotData.Log;
import MyLib.LotData.LotData;
import MyApp.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import java.lang.Math;  
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Angela
 */
public class Report extends javax.swing.JFrame {
    private Form form;
    private static Report instance;
    
    
    public Report(Form form) {
        this.form = form;
        initComponents();
        
        initializeWindow();
    }
    /**
     * Creates new form Report
     */
    public Report() {
        initComponents();
    }

     public static Report getInstance() {
        if (instance == null) {
            instance = new Report();
        }
        return instance;
    }
     
    public void generateReport(){
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) form.getjTable1().getModel();
        
        Log log = Log.getInstance();
        LotData d = LotData.getInstance();
        //Reserved
        report_num_reserved.setText(String.valueOf(log.totalReserved)); 
        //Sold
        report_num_sold.setText(String.valueOf(log.totalSold)); 
        //Pending Reservations
        report_num_pReservations.setText(String.valueOf(log.totalPendingReservations));
        //Pending Sold
        report_num_pPayments.setText(String.valueOf(log.totalPendingPayments));
        
        report_pReservations.setVisible(true);
        report_pPayments.setVisible(true);
        report_num_pReservations.setVisible(true);
        report_num_pPayments.setVisible(true);
        
        report_Reserved.setVisible(true);
        report_Sold.setVisible(true);
        report_num_reserved.setVisible(true);
        report_num_sold.setVisible(true);

        model.setRowCount(0);

        for (int j=0; j<d.getMySub().getMaxBlock(); j++)
        {
            for (int i=0; i<d.getMySub().getBlockArray()[j].getMaxLot();i++)
            {
                int blockNum = d.getMySub().getBlockArray()[j].getBlockNum();
                int lotNum = d.getMySub().getBlockArray()[j].getLotArray()[i].getLotNum();
                int lotSize = d.getMySub().getBlockArray()[j].getLotArray()[i].getLotSize();
                String priceString = d.getMySub().getBlockArray()[j].getLotArray()[i].getPrice().generatePriceString();
                String lotStatus = d.getMySub().getBlockArray()[j].getLotArray()[i].getLotStatus();
                model.insertRow(model.getRowCount(),new Object[]{blockNum,lotNum, lotSize, priceString, lotStatus});
            }
        }
        for (int i = 0; i < 30 - form.lotTable.getRowCount(); i++) {
        model.addRow(new Object[]{null, null, null, null});
        }
    }
    
    private void initializeWindow() {
        setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);

        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                // Hide the window instead of closing
                setVisible(false);
            }
        });
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        report_pReservations = new javax.swing.JLabel();
        report_Reserved = new javax.swing.JLabel();
        report_pPayments = new javax.swing.JLabel();
        report_Sold = new javax.swing.JLabel();
        report_status = new javax.swing.JLabel();
        report_num_label = new javax.swing.JLabel();
        report_num_pReservations = new javax.swing.JLabel();
        report_num_reserved = new javax.swing.JLabel();
        report_num_pPayments = new javax.swing.JLabel();
        report_num_sold = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        report_pReservations.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        report_pReservations.setText("Pending Reservations");

        report_Reserved.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        report_Reserved.setText("Reserved Lots");

        report_pPayments.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        report_pPayments.setText("Pending Payments");

        report_Sold.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        report_Sold.setText("Sold Lots");

        report_status.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        report_status.setText("Status");

        report_num_label.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        report_num_label.setText("Number of Lots");

        report_num_pReservations.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        report_num_pReservations.setText("0");

        report_num_reserved.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        report_num_reserved.setText("0");

        report_num_pPayments.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        report_num_pPayments.setText("0");

        report_num_sold.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        report_num_sold.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(report_pReservations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(report_Reserved, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(report_pPayments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(report_Sold, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 79, 79)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(report_num_reserved)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(report_num_pReservations)
                                .addComponent(report_num_pPayments, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(report_num_sold, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(report_status)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                        .addComponent(report_num_label)
                        .addGap(80, 80, 80))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(report_status)
                    .addComponent(report_num_label, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(report_pReservations, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(report_num_pReservations))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(report_Reserved)
                    .addComponent(report_num_reserved))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(report_pPayments)
                    .addComponent(report_num_pPayments))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(report_Sold)
                    .addComponent(report_num_sold))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Report().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel report_Reserved;
    private javax.swing.JLabel report_Sold;
    private javax.swing.JLabel report_num_label;
    private javax.swing.JLabel report_num_pPayments;
    private javax.swing.JLabel report_num_pReservations;
    private javax.swing.JLabel report_num_reserved;
    private javax.swing.JLabel report_num_sold;
    private javax.swing.JLabel report_pPayments;
    private javax.swing.JLabel report_pReservations;
    private javax.swing.JLabel report_status;
    // End of variables declaration//GEN-END:variables
}
